// <auto-generated />
using ApiMGIC.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiMGIC.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiMGIC.Model.Assigne.assigne", b =>
                {
                    b.Property<string>("idS")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("celula")
                        .IsRequired();

                    b.Property<string>("cvepuesto")
                        .IsRequired();

                    b.Property<string>("fialfa")
                        .IsRequired();

                    b.Property<string>("fipuesto")
                        .IsRequired();

                    b.Property<string>("idpuesto")
                        .IsRequired();

                    b.Property<string>("jefeinm")
                        .IsRequired();

                    b.Property<string>("nivel")
                        .IsRequired();

                    b.Property<string>("nombre")
                        .IsRequired();

                    b.Property<string>("nombre_ji")
                        .IsRequired();

                    b.Property<string>("numero")
                        .IsRequired();

                    b.Property<string>("puesto")
                        .IsRequired();

                    b.Property<string>("site")
                        .IsRequired();

                    b.Property<string>("subdiv")
                        .IsRequired();

                    b.Property<string>("unidadorg")
                        .IsRequired();

                    b.HasKey("idS");

                    b.ToTable("assigne");
                });

            modelBuilder.Entity("ApiMGIC.Model.Store.store", b =>
                {
                    b.Property<string>("idS")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Dirección")
                        .IsRequired();

                    b.Property<string>("Gpoclientes")
                        .IsRequired();

                    b.Property<string>("Interlocutor")
                        .IsRequired();

                    b.Property<string>("OficinadeVentas")
                        .IsRequired();

                    b.Property<string>("Poblacion")
                        .IsRequired();

                    b.Property<string>("RutaSOL")
                        .IsRequired();

                    b.Property<string>("Sector")
                        .IsRequired();

                    b.Property<string>("Segment")
                        .IsRequired();

                    b.Property<string>("Zonadeventas")
                        .IsRequired();

                    b.Property<string>("customernumber")
                        .IsRequired();

                    b.Property<string>("distributionchannel")
                        .IsRequired();

                    b.Property<string>("latitud")
                        .IsRequired();

                    b.Property<string>("longitud")
                        .IsRequired();

                    b.Property<string>("name1")
                        .IsRequired();

                    b.Property<string>("name2")
                        .IsRequired();

                    b.Property<string>("region")
                        .IsRequired();

                    b.Property<string>("salesorganization")
                        .IsRequired();

                    b.Property<string>("streetandnumber")
                        .IsRequired();

                    b.Property<string>("zipcode")
                        .IsRequired();

                    b.HasKey("idS");

                    b.ToTable("stores");
                });
#pragma warning restore 612, 618
        }
    }
}
